openapi: 3.0.3
info:
  title: Storage node API
  description: Storage node API
  contact:
    email: info@joystream.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.1.0
externalDocs:
  description: Storage node API
  url: joystream.org
servers:
- url: /api/v1
 
tags:
  - name: greeting
    description: Greeting APIs
 
paths:
  /hello/{name}:
    get:
      operationId: greeting.hello
      description: Returns 'Hello <name>/stranger!!!' to the caller
      tags: 
        - greeting
      parameters:
      - name: name
        required: true
        in: path
        description: The name of a caller
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
  /upload:
    post:
      description: Upload data
      operationId: publicApi.upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              # $ref: '#/components/schemas/NewPhoto'
              type: object
              required:
                - recfile
              properties:
                file:
                  description: Data file
                  type: string
                  format: binary
        required: true
      responses:
        200:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean

components:
  schemas:
    HelloResponse:
      type: object
      additionalProperties: false
      required:
        - message
      properties:
        message:
          type: string